version: '3'

services:
  scraper:
    image: moviecast-scraper
    build: .
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: moviecast-scraper
    ports:
      - 3000:3000
  mongo:
    image: mongo
